package main.java.com.cskaoyan.mall.mapper;

import com.cskaoyan.bean.cskaoyan_mall_comment;
import com.cskaoyan.bean.cskaoyan_mall_commentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface cskaoyan_mall_commentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_comment
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    long countByExample(cskaoyan_mall_commentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_comment
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    int deleteByExample(cskaoyan_mall_commentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_comment
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_comment
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    int insert(cskaoyan_mall_comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_comment
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    int insertSelective(cskaoyan_mall_comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_comment
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    List<cskaoyan_mall_comment> selectByExample(cskaoyan_mall_commentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_comment
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    cskaoyan_mall_comment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_comment
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") cskaoyan_mall_comment record, @Param("example") cskaoyan_mall_commentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_comment
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    int updateByExample(@Param("record") cskaoyan_mall_comment record, @Param("example") cskaoyan_mall_commentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_comment
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    int updateByPrimaryKeySelective(cskaoyan_mall_comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_comment
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    int updateByPrimaryKey(cskaoyan_mall_comment record);
}
