package main.java.com.cskaoyan.mall.mapper;

import com.cskaoyan.mall.bean.cskaoyan_mall_permission;
import com.cskaoyan.mall.bean.cskaoyan_mall_permissionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface cskaoyan_mall_permissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_permission
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    long countByExample(cskaoyan_mall_permissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_permission
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    int deleteByExample(cskaoyan_mall_permissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_permission
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_permission
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    int insert(cskaoyan_mall_permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_permission
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    int insertSelective(cskaoyan_mall_permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_permission
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    List<cskaoyan_mall_permission> selectByExample(cskaoyan_mall_permissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_permission
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    cskaoyan_mall_permission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_permission
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") cskaoyan_mall_permission record, @Param("example") cskaoyan_mall_permissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_permission
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    int updateByExample(@Param("record") cskaoyan_mall_permission record, @Param("example") cskaoyan_mall_permissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_permission
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    int updateByPrimaryKeySelective(cskaoyan_mall_permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_permission
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    int updateByPrimaryKey(cskaoyan_mall_permission record);
}
