package main.java.com.cskaoyan.mall.mapper;

import com.cskaoyan.mall.bean.cskaoyan_mall_user;
import com.cskaoyan.mall.bean.cskaoyan_mall_userExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface cskaoyan_mall_userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_user
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    long countByExample(cskaoyan_mall_userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_user
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    int deleteByExample(cskaoyan_mall_userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_user
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_user
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    int insert(cskaoyan_mall_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_user
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    int insertSelective(cskaoyan_mall_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_user
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    List<cskaoyan_mall_user> selectByExample(cskaoyan_mall_userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_user
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    cskaoyan_mall_user selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_user
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") cskaoyan_mall_user record, @Param("example") cskaoyan_mall_userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_user
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    int updateByExample(@Param("record") cskaoyan_mall_user record, @Param("example") cskaoyan_mall_userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_user
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    int updateByPrimaryKeySelective(cskaoyan_mall_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cskaoyan_mall_user
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    int updateByPrimaryKey(cskaoyan_mall_user record);
}
