package main.java.com.cskaoyan.mall.bean;

import java.math.BigDecimal;
import java.util.Date;

public class cskaoyan_mall_groupon_rules {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon_rules.id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon_rules.goods_id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon_rules.goods_name
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon_rules.pic_url
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon_rules.discount
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private BigDecimal discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon_rules.discount_member
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Integer discountMember;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon_rules.add_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon_rules.update_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon_rules.expire_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon_rules.deleted
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon_rules.id
     *
     * @return the value of cskaoyan_mall_groupon_rules.id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon_rules.id
     *
     * @param id the value for cskaoyan_mall_groupon_rules.id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon_rules.goods_id
     *
     * @return the value of cskaoyan_mall_groupon_rules.goods_id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon_rules.goods_id
     *
     * @param goodsId the value for cskaoyan_mall_groupon_rules.goods_id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon_rules.goods_name
     *
     * @return the value of cskaoyan_mall_groupon_rules.goods_name
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon_rules.goods_name
     *
     * @param goodsName the value for cskaoyan_mall_groupon_rules.goods_name
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon_rules.pic_url
     *
     * @return the value of cskaoyan_mall_groupon_rules.pic_url
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon_rules.pic_url
     *
     * @param picUrl the value for cskaoyan_mall_groupon_rules.pic_url
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon_rules.discount
     *
     * @return the value of cskaoyan_mall_groupon_rules.discount
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon_rules.discount
     *
     * @param discount the value for cskaoyan_mall_groupon_rules.discount
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon_rules.discount_member
     *
     * @return the value of cskaoyan_mall_groupon_rules.discount_member
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Integer getDiscountMember() {
        return discountMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon_rules.discount_member
     *
     * @param discountMember the value for cskaoyan_mall_groupon_rules.discount_member
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setDiscountMember(Integer discountMember) {
        this.discountMember = discountMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon_rules.add_time
     *
     * @return the value of cskaoyan_mall_groupon_rules.add_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon_rules.add_time
     *
     * @param addTime the value for cskaoyan_mall_groupon_rules.add_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon_rules.update_time
     *
     * @return the value of cskaoyan_mall_groupon_rules.update_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon_rules.update_time
     *
     * @param updateTime the value for cskaoyan_mall_groupon_rules.update_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon_rules.expire_time
     *
     * @return the value of cskaoyan_mall_groupon_rules.expire_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon_rules.expire_time
     *
     * @param expireTime the value for cskaoyan_mall_groupon_rules.expire_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon_rules.deleted
     *
     * @return the value of cskaoyan_mall_groupon_rules.deleted
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon_rules.deleted
     *
     * @param deleted the value for cskaoyan_mall_groupon_rules.deleted
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}
