package main.java.com.cskaoyan.mall.bean;

import java.util.Date;

public class cskaoyan_mall_log {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_log.id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_log.admin
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private String admin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_log.ip
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_log.type
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_log.action
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_log.status
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_log.result
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_log.comment
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_log.add_time
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_log.update_time
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_log.deleted
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_log.id
     *
     * @return the value of cskaoyan_mall_log.id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_log.id
     *
     * @param id the value for cskaoyan_mall_log.id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_log.admin
     *
     * @return the value of cskaoyan_mall_log.admin
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public String getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_log.admin
     *
     * @param admin the value for cskaoyan_mall_log.admin
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setAdmin(String admin) {
        this.admin = admin == null ? null : admin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_log.ip
     *
     * @return the value of cskaoyan_mall_log.ip
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_log.ip
     *
     * @param ip the value for cskaoyan_mall_log.ip
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_log.type
     *
     * @return the value of cskaoyan_mall_log.type
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_log.type
     *
     * @param type the value for cskaoyan_mall_log.type
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_log.action
     *
     * @return the value of cskaoyan_mall_log.action
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_log.action
     *
     * @param action the value for cskaoyan_mall_log.action
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_log.status
     *
     * @return the value of cskaoyan_mall_log.status
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_log.status
     *
     * @param status the value for cskaoyan_mall_log.status
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_log.result
     *
     * @return the value of cskaoyan_mall_log.result
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_log.result
     *
     * @param result the value for cskaoyan_mall_log.result
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_log.comment
     *
     * @return the value of cskaoyan_mall_log.comment
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_log.comment
     *
     * @param comment the value for cskaoyan_mall_log.comment
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_log.add_time
     *
     * @return the value of cskaoyan_mall_log.add_time
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_log.add_time
     *
     * @param addTime the value for cskaoyan_mall_log.add_time
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_log.update_time
     *
     * @return the value of cskaoyan_mall_log.update_time
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_log.update_time
     *
     * @param updateTime the value for cskaoyan_mall_log.update_time
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_log.deleted
     *
     * @return the value of cskaoyan_mall_log.deleted
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_log.deleted
     *
     * @param deleted the value for cskaoyan_mall_log.deleted
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}
