package main.java.com.cskaoyan.mall.bean;

import java.util.Date;

public class cskaoyan_mall_search_history {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_user_formid.id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_user_formid.formId
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String formid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_user_formid.isprepay
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Boolean isprepay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_user_formid.useAmount
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Integer useamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_user_formid.expire_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_user_formid.openId
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_user_formid.add_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_user_formid.update_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_user_formid.deleted
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_user_formid.id
     *
     * @return the value of cskaoyan_mall_user_formid.id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_user_formid.id
     *
     * @param id the value for cskaoyan_mall_user_formid.id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_user_formid.formId
     *
     * @return the value of cskaoyan_mall_user_formid.formId
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getFormid() {
        return formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_user_formid.formId
     *
     * @param formid the value for cskaoyan_mall_user_formid.formId
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setFormid(String formid) {
        this.formid = formid == null ? null : formid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_user_formid.isprepay
     *
     * @return the value of cskaoyan_mall_user_formid.isprepay
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Boolean getIsprepay() {
        return isprepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_user_formid.isprepay
     *
     * @param isprepay the value for cskaoyan_mall_user_formid.isprepay
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setIsprepay(Boolean isprepay) {
        this.isprepay = isprepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_user_formid.useAmount
     *
     * @return the value of cskaoyan_mall_user_formid.useAmount
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Integer getUseamount() {
        return useamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_user_formid.useAmount
     *
     * @param useamount the value for cskaoyan_mall_user_formid.useAmount
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setUseamount(Integer useamount) {
        this.useamount = useamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_user_formid.expire_time
     *
     * @return the value of cskaoyan_mall_user_formid.expire_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_user_formid.expire_time
     *
     * @param expireTime the value for cskaoyan_mall_user_formid.expire_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_user_formid.openId
     *
     * @return the value of cskaoyan_mall_user_formid.openId
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_user_formid.openId
     *
     * @param openid the value for cskaoyan_mall_user_formid.openId
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_user_formid.add_time
     *
     * @return the value of cskaoyan_mall_user_formid.add_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_user_formid.add_time
     *
     * @param addTime the value for cskaoyan_mall_user_formid.add_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_user_formid.update_time
     *
     * @return the value of cskaoyan_mall_user_formid.update_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_user_formid.update_time
     *
     * @param updateTime the value for cskaoyan_mall_user_formid.update_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_user_formid.deleted
     *
     * @return the value of cskaoyan_mall_user_formid.deleted
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_user_formid.deleted
     *
     * @param deleted the value for cskaoyan_mall_user_formid.deleted
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}
