package main.java.com.cskaoyan.mall.bean;

import java.util.Date;

public class cskaoyan_mall_groupon {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon.id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon.order_id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon.groupon_id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Integer grouponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon.rules_id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Integer rulesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon.user_id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon.creator_user_id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Integer creatorUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon.add_time
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon.update_time
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon.share_url
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private String shareUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon.payed
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Boolean payed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_groupon.deleted
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon.id
     *
     * @return the value of cskaoyan_mall_groupon.id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon.id
     *
     * @param id the value for cskaoyan_mall_groupon.id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon.order_id
     *
     * @return the value of cskaoyan_mall_groupon.order_id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon.order_id
     *
     * @param orderId the value for cskaoyan_mall_groupon.order_id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon.groupon_id
     *
     * @return the value of cskaoyan_mall_groupon.groupon_id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Integer getGrouponId() {
        return grouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon.groupon_id
     *
     * @param grouponId the value for cskaoyan_mall_groupon.groupon_id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setGrouponId(Integer grouponId) {
        this.grouponId = grouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon.rules_id
     *
     * @return the value of cskaoyan_mall_groupon.rules_id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Integer getRulesId() {
        return rulesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon.rules_id
     *
     * @param rulesId the value for cskaoyan_mall_groupon.rules_id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setRulesId(Integer rulesId) {
        this.rulesId = rulesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon.user_id
     *
     * @return the value of cskaoyan_mall_groupon.user_id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon.user_id
     *
     * @param userId the value for cskaoyan_mall_groupon.user_id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon.creator_user_id
     *
     * @return the value of cskaoyan_mall_groupon.creator_user_id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Integer getCreatorUserId() {
        return creatorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon.creator_user_id
     *
     * @param creatorUserId the value for cskaoyan_mall_groupon.creator_user_id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setCreatorUserId(Integer creatorUserId) {
        this.creatorUserId = creatorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon.add_time
     *
     * @return the value of cskaoyan_mall_groupon.add_time
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon.add_time
     *
     * @param addTime the value for cskaoyan_mall_groupon.add_time
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon.update_time
     *
     * @return the value of cskaoyan_mall_groupon.update_time
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon.update_time
     *
     * @param updateTime the value for cskaoyan_mall_groupon.update_time
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon.share_url
     *
     * @return the value of cskaoyan_mall_groupon.share_url
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public String getShareUrl() {
        return shareUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon.share_url
     *
     * @param shareUrl the value for cskaoyan_mall_groupon.share_url
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setShareUrl(String shareUrl) {
        this.shareUrl = shareUrl == null ? null : shareUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon.payed
     *
     * @return the value of cskaoyan_mall_groupon.payed
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Boolean getPayed() {
        return payed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon.payed
     *
     * @param payed the value for cskaoyan_mall_groupon.payed
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setPayed(Boolean payed) {
        this.payed = payed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_groupon.deleted
     *
     * @return the value of cskaoyan_mall_groupon.deleted
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_groupon.deleted
     *
     * @param deleted the value for cskaoyan_mall_groupon.deleted
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}
