package com.cskaoyan.mall.bean;

import java.math.BigDecimal;
import java.util.Date;

public class cskaoyan_mall_order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.user_id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.order_sn
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String orderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.order_status
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Short orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.consignee
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.mobile
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.address
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.message
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.goods_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.freight_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private BigDecimal freightPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.coupon_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private BigDecimal couponPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.integral_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private BigDecimal integralPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.groupon_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private BigDecimal grouponPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.order_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private BigDecimal orderPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.actual_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private BigDecimal actualPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.pay_id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.pay_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.ship_sn
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String shipSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.ship_channel
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String shipChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.ship_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Date shipTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.confirm_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Date confirmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.comments
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Short comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.end_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.add_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.update_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_order.deleted
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.id
     *
     * @return the value of cskaoyan_mall_order.id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.id
     *
     * @param id the value for cskaoyan_mall_order.id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.user_id
     *
     * @return the value of cskaoyan_mall_order.user_id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.user_id
     *
     * @param userId the value for cskaoyan_mall_order.user_id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.order_sn
     *
     * @return the value of cskaoyan_mall_order.order_sn
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.order_sn
     *
     * @param orderSn the value for cskaoyan_mall_order.order_sn
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.order_status
     *
     * @return the value of cskaoyan_mall_order.order_status
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Short getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.order_status
     *
     * @param orderStatus the value for cskaoyan_mall_order.order_status
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setOrderStatus(Short orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.consignee
     *
     * @return the value of cskaoyan_mall_order.consignee
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.consignee
     *
     * @param consignee the value for cskaoyan_mall_order.consignee
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.mobile
     *
     * @return the value of cskaoyan_mall_order.mobile
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.mobile
     *
     * @param mobile the value for cskaoyan_mall_order.mobile
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.address
     *
     * @return the value of cskaoyan_mall_order.address
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.address
     *
     * @param address the value for cskaoyan_mall_order.address
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.message
     *
     * @return the value of cskaoyan_mall_order.message
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.message
     *
     * @param message the value for cskaoyan_mall_order.message
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.goods_price
     *
     * @return the value of cskaoyan_mall_order.goods_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.goods_price
     *
     * @param goodsPrice the value for cskaoyan_mall_order.goods_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.freight_price
     *
     * @return the value of cskaoyan_mall_order.freight_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public BigDecimal getFreightPrice() {
        return freightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.freight_price
     *
     * @param freightPrice the value for cskaoyan_mall_order.freight_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setFreightPrice(BigDecimal freightPrice) {
        this.freightPrice = freightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.coupon_price
     *
     * @return the value of cskaoyan_mall_order.coupon_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public BigDecimal getCouponPrice() {
        return couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.coupon_price
     *
     * @param couponPrice the value for cskaoyan_mall_order.coupon_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setCouponPrice(BigDecimal couponPrice) {
        this.couponPrice = couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.integral_price
     *
     * @return the value of cskaoyan_mall_order.integral_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public BigDecimal getIntegralPrice() {
        return integralPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.integral_price
     *
     * @param integralPrice the value for cskaoyan_mall_order.integral_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setIntegralPrice(BigDecimal integralPrice) {
        this.integralPrice = integralPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.groupon_price
     *
     * @return the value of cskaoyan_mall_order.groupon_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public BigDecimal getGrouponPrice() {
        return grouponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.groupon_price
     *
     * @param grouponPrice the value for cskaoyan_mall_order.groupon_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setGrouponPrice(BigDecimal grouponPrice) {
        this.grouponPrice = grouponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.order_price
     *
     * @return the value of cskaoyan_mall_order.order_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.order_price
     *
     * @param orderPrice the value for cskaoyan_mall_order.order_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.actual_price
     *
     * @return the value of cskaoyan_mall_order.actual_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public BigDecimal getActualPrice() {
        return actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.actual_price
     *
     * @param actualPrice the value for cskaoyan_mall_order.actual_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setActualPrice(BigDecimal actualPrice) {
        this.actualPrice = actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.pay_id
     *
     * @return the value of cskaoyan_mall_order.pay_id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.pay_id
     *
     * @param payId the value for cskaoyan_mall_order.pay_id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setPayId(String payId) {
        this.payId = payId == null ? null : payId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.pay_time
     *
     * @return the value of cskaoyan_mall_order.pay_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.pay_time
     *
     * @param payTime the value for cskaoyan_mall_order.pay_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.ship_sn
     *
     * @return the value of cskaoyan_mall_order.ship_sn
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getShipSn() {
        return shipSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.ship_sn
     *
     * @param shipSn the value for cskaoyan_mall_order.ship_sn
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setShipSn(String shipSn) {
        this.shipSn = shipSn == null ? null : shipSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.ship_channel
     *
     * @return the value of cskaoyan_mall_order.ship_channel
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getShipChannel() {
        return shipChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.ship_channel
     *
     * @param shipChannel the value for cskaoyan_mall_order.ship_channel
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setShipChannel(String shipChannel) {
        this.shipChannel = shipChannel == null ? null : shipChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.ship_time
     *
     * @return the value of cskaoyan_mall_order.ship_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Date getShipTime() {
        return shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.ship_time
     *
     * @param shipTime the value for cskaoyan_mall_order.ship_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setShipTime(Date shipTime) {
        this.shipTime = shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.confirm_time
     *
     * @return the value of cskaoyan_mall_order.confirm_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Date getConfirmTime() {
        return confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.confirm_time
     *
     * @param confirmTime the value for cskaoyan_mall_order.confirm_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setConfirmTime(Date confirmTime) {
        this.confirmTime = confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.comments
     *
     * @return the value of cskaoyan_mall_order.comments
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Short getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.comments
     *
     * @param comments the value for cskaoyan_mall_order.comments
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setComments(Short comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.end_time
     *
     * @return the value of cskaoyan_mall_order.end_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.end_time
     *
     * @param endTime the value for cskaoyan_mall_order.end_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.add_time
     *
     * @return the value of cskaoyan_mall_order.add_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.add_time
     *
     * @param addTime the value for cskaoyan_mall_order.add_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.update_time
     *
     * @return the value of cskaoyan_mall_order.update_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.update_time
     *
     * @param updateTime the value for cskaoyan_mall_order.update_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_order.deleted
     *
     * @return the value of cskaoyan_mall_order.deleted
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_order.deleted
     *
     * @param deleted the value for cskaoyan_mall_order.deleted
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}
