package main.java.com.cskaoyan.mall.bean;

public class cskaoyan_mall_region {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_region.id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_region.pid
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_region.name
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_region.type
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_region.code
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    private Integer code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_region.id
     *
     * @return the value of cskaoyan_mall_region.id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_region.id
     *
     * @param id the value for cskaoyan_mall_region.id
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_region.pid
     *
     * @return the value of cskaoyan_mall_region.pid
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_region.pid
     *
     * @param pid the value for cskaoyan_mall_region.pid
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_region.name
     *
     * @return the value of cskaoyan_mall_region.name
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_region.name
     *
     * @param name the value for cskaoyan_mall_region.name
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_region.type
     *
     * @return the value of cskaoyan_mall_region.type
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_region.type
     *
     * @param type the value for cskaoyan_mall_region.type
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_region.code
     *
     * @return the value of cskaoyan_mall_region.code
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_region.code
     *
     * @param code the value for cskaoyan_mall_region.code
     *
     * @mbg.generated Mon Sep 30 12:00:17 CST 2019
     */
    public void setCode(Integer code) {
        this.code = code;
    }
}
