package com.cskaoyan.mall.bean;

import java.math.BigDecimal;
import java.util.Date;

public class cskaoyan_mall_goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.goods_sn
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String goodsSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.name
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.category_id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.brand_id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.gallery
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String gallery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.keywords
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.brief
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String brief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.is_on_sale
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Boolean isOnSale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.sort_order
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Short sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.pic_url
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.share_url
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String shareUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.is_new
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Boolean isNew;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.is_hot
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Boolean isHot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.unit
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.counter_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private BigDecimal counterPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.retail_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private BigDecimal retailPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.add_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.update_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.deleted
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cskaoyan_mall_goods.detail
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.id
     *
     * @return the value of cskaoyan_mall_goods.id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.id
     *
     * @param id the value for cskaoyan_mall_goods.id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.goods_sn
     *
     * @return the value of cskaoyan_mall_goods.goods_sn
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.goods_sn
     *
     * @param goodsSn the value for cskaoyan_mall_goods.goods_sn
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.name
     *
     * @return the value of cskaoyan_mall_goods.name
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.name
     *
     * @param name the value for cskaoyan_mall_goods.name
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.category_id
     *
     * @return the value of cskaoyan_mall_goods.category_id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.category_id
     *
     * @param categoryId the value for cskaoyan_mall_goods.category_id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.brand_id
     *
     * @return the value of cskaoyan_mall_goods.brand_id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.brand_id
     *
     * @param brandId the value for cskaoyan_mall_goods.brand_id
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.gallery
     *
     * @return the value of cskaoyan_mall_goods.gallery
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getGallery() {
        return gallery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.gallery
     *
     * @param gallery the value for cskaoyan_mall_goods.gallery
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setGallery(String gallery) {
        this.gallery = gallery == null ? null : gallery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.keywords
     *
     * @return the value of cskaoyan_mall_goods.keywords
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.keywords
     *
     * @param keywords the value for cskaoyan_mall_goods.keywords
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.brief
     *
     * @return the value of cskaoyan_mall_goods.brief
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.brief
     *
     * @param brief the value for cskaoyan_mall_goods.brief
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.is_on_sale
     *
     * @return the value of cskaoyan_mall_goods.is_on_sale
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Boolean getIsOnSale() {
        return isOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.is_on_sale
     *
     * @param isOnSale the value for cskaoyan_mall_goods.is_on_sale
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setIsOnSale(Boolean isOnSale) {
        this.isOnSale = isOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.sort_order
     *
     * @return the value of cskaoyan_mall_goods.sort_order
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Short getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.sort_order
     *
     * @param sortOrder the value for cskaoyan_mall_goods.sort_order
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setSortOrder(Short sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.pic_url
     *
     * @return the value of cskaoyan_mall_goods.pic_url
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.pic_url
     *
     * @param picUrl the value for cskaoyan_mall_goods.pic_url
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.share_url
     *
     * @return the value of cskaoyan_mall_goods.share_url
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getShareUrl() {
        return shareUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.share_url
     *
     * @param shareUrl the value for cskaoyan_mall_goods.share_url
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setShareUrl(String shareUrl) {
        this.shareUrl = shareUrl == null ? null : shareUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.is_new
     *
     * @return the value of cskaoyan_mall_goods.is_new
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Boolean getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.is_new
     *
     * @param isNew the value for cskaoyan_mall_goods.is_new
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setIsNew(Boolean isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.is_hot
     *
     * @return the value of cskaoyan_mall_goods.is_hot
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Boolean getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.is_hot
     *
     * @param isHot the value for cskaoyan_mall_goods.is_hot
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setIsHot(Boolean isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.unit
     *
     * @return the value of cskaoyan_mall_goods.unit
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.unit
     *
     * @param unit the value for cskaoyan_mall_goods.unit
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.counter_price
     *
     * @return the value of cskaoyan_mall_goods.counter_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public BigDecimal getCounterPrice() {
        return counterPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.counter_price
     *
     * @param counterPrice the value for cskaoyan_mall_goods.counter_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setCounterPrice(BigDecimal counterPrice) {
        this.counterPrice = counterPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.retail_price
     *
     * @return the value of cskaoyan_mall_goods.retail_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public BigDecimal getRetailPrice() {
        return retailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.retail_price
     *
     * @param retailPrice the value for cskaoyan_mall_goods.retail_price
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setRetailPrice(BigDecimal retailPrice) {
        this.retailPrice = retailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.add_time
     *
     * @return the value of cskaoyan_mall_goods.add_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.add_time
     *
     * @param addTime the value for cskaoyan_mall_goods.add_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.update_time
     *
     * @return the value of cskaoyan_mall_goods.update_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.update_time
     *
     * @param updateTime the value for cskaoyan_mall_goods.update_time
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.deleted
     *
     * @return the value of cskaoyan_mall_goods.deleted
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.deleted
     *
     * @param deleted the value for cskaoyan_mall_goods.deleted
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cskaoyan_mall_goods.detail
     *
     * @return the value of cskaoyan_mall_goods.detail
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cskaoyan_mall_goods.detail
     *
     * @param detail the value for cskaoyan_mall_goods.detail
     *
     * @mbg.generated Mon Sep 30 14:11:59 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}
